# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit設定ファイル - 日本語でのレビューを有効化
language: "ja-JP"
early_access: false
enable_free_tier: true
tone_instructions: |
  - レビューは日本語で行ってください
  - 専門用語は適切に日本語化してください
  - コードのコメントは英語のままで構いません
knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
chat:
  auto_reply: true
reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: false
  poem: false
  review_status: true
  collapse_walkthrough: true